---
info:
  title: Rex Core
  description: Created by David Maloney via the GitHub Connector
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/rex-core
  x-cortex-tag: rex-core
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
